# Generated by Django 3.2.6 on 2021-08-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publicSetting', models.BooleanField()),
                ('password_Post', models.IntegerField()),
                ('age_tag', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='community/')),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
