# Generated by Django 3.2.6 on 2021-08-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='replyCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
