# Generated by Django 3.2.3 on 2021-08-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
