# Generated by Django 3.2.6 on 2021-08-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='password_Post',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
