# Generated by Django 3.2.3 on 2021-08-11 03:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_auto_20210811_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertre',
            name='likes_user',
            field=models.ManyToManyField(blank=True, default=0, related_name='likes_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
