# Generated by Django 3.2.6 on 2021-08-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_community_password_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publicSetting', models.BooleanField()),
                ('password_Post', models.IntegerField(blank=True, null=True)),
                ('age_tag', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='community/')),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
