# Generated by Django 3.2.6 on 2021-08-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20210811_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='replyCount',
        ),
        migrations.AddField(
            model_name='reply',
            name='replyCount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
