# Generated by Django 3.2.6 on 2021-08-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_reply_replycount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='replyCount',
        ),
        migrations.AddField(
            model_name='community',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
