# Generated by Django 3.2.5 on 2021-08-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20210810_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='password_Post',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
