# Generated by Django 3.2.6 on 2021-08-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_community_password_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='password_Post',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
