# Generated by Django 3.2.6 on 2021-08-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_expertre'),
        ('community', '0006_alter_expert_password_post'),
    ]

    operations = [
    ]
