# Generated by Django 3.2.3 on 2021-08-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_reply'),
        ('community', '0008_reply'),
    ]

    operations = [
    ]
